[package]
name = "cage-tree"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cage-core = { workspace = true }
cage-mongodb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
